#ifndef TEESMC_TKCORED_H
#define TEESMC_TKCORED_H

#define TEESMC_TKCORED_FUNCID_RETURN_ENTRY_DONE		0
#define TEESMC32_TKCORED_RETURN_ENTRY_DONE \
	TEESMC_CALL_VAL(TEESMC_32, TEESMC_FAST_CALL, \
			TEESMC_OWNER_TRUSTED_OS_TKCORED, \
			TEESMC_TKCORED_FUNCID_RETURN_ENTRY_DONE)
#define TEESMC64_TKCORED_RETURN_ENTRY_DONE \
	TEESMC_CALL_VAL(TEESMC_64, TEESMC_FAST_CALL, \
			TEESMC_OWNER_TRUSTED_OS_TKCORED, \
			TEESMC_TKCORED_FUNCID_RETURN_ENTRY_DONE)


#define TEESMC_TKCORED_FUNCID_RETURN_ON_DONE		1
#define TEESMC32_TKCORED_RETURN_ON_DONE \
	TEESMC_CALL_VAL(TEESMC_32, TEESMC_FAST_CALL, \
			TEESMC_OWNER_TRUSTED_OS_TKCORED, \
			TEESMC_TKCORED_FUNCID_RETURN_ON_DONE)
#define TEESMC64_TKCORED_RETURN_ON_DONE \
	TEESMC_CALL_VAL(TEESMC_64, TEESMC_FAST_CALL, \
			TEESMC_OWNER_TRUSTED_OS_TKCORED, \
			TEESMC_TKCORED_FUNCID_RETURN_ON_DONE)


#define TEESMC_TKCORED_FUNCID_RETURN_OFF_DONE		2
#define TEESMC32_TKCORED_RETURN_OFF_DONE \
	TEESMC_CALL_VAL(TEESMC_32, TEESMC_FAST_CALL, \
			TEESMC_OWNER_TRUSTED_OS_TKCORED, \
			TEESMC_TKCORED_FUNCID_RETURN_OFF_DONE)
#define TEESMC64_TKCORED_RETURN_OFF_DONE \
	TEESMC_CALL_VAL(TEESMC_64, TEESMC_FAST_CALL, \
			TEESMC_OWNER_TRUSTED_OS_TKCORED, \
			TEESMC_TKCORED_FUNCID_RETURN_OFF_DONE)


#define TEESMC_TKCORED_FUNCID_RETURN_SUSPEND_DONE	3
#define TEESMC32_TKCORED_RETURN_SUSPEND_DONE \
	TEESMC_CALL_VAL(TEESMC_32, TEESMC_FAST_CALL, \
			TEESMC_OWNER_TRUSTED_OS_TKCORED, \
			TEESMC_TKCORED_FUNCID_RETURN_SUSPEND_DONE)
#define TEESMC64_TKCORED_RETURN_SUSPEND_DONE \
	TEESMC_CALL_VAL(TEESMC_64, TEESMC_FAST_CALL, \
			TEESMC_OWNER_TRUSTED_OS_TKCORED, \
			TEESMC_TKCORED_FUNCID_RETURN_SUSPEND_DONE)

#define TEESMC_TKCORED_FUNCID_RETURN_RESUME_DONE		4
#define TEESMC32_TKCORED_RETURN_RESUME_DONE \
	TEESMC_CALL_VAL(TEESMC_32, TEESMC_FAST_CALL, \
			TEESMC_OWNER_TRUSTED_OS_TKCORED, \
			TEESMC_TKCORED_FUNCID_RETURN_RESUME_DONE)
#define TEESMC64_TKCORED_RETURN_RESUME_DONE \
	TEESMC_CALL_VAL(TEESMC_64, TEESMC_FAST_CALL, \
			TEESMC_OWNER_TRUSTED_OS_TKCORED, \
			TEESMC_TKCORED_FUNCID_RETURN_RESUME_DONE)

#define TEESMC_TKCORED_FUNCID_RETURN_CALL_DONE		5
#define TEESMC32_TKCORED_RETURN_CALL_DONE \
	TEESMC_CALL_VAL(TEESMC_32, TEESMC_FAST_CALL, \
			TEESMC_OWNER_TRUSTED_OS_TKCORED, \
			TEESMC_TKCORED_FUNCID_RETURN_CALL_DONE)
#define TEESMC64_TKCORED_RETURN_CALL_DONE \
	TEESMC_CALL_VAL(TEESMC_64, TEESMC_FAST_CALL, \
			TEESMC_OWNER_TRUSTED_OS_TKCORED, \
			TEESMC_TKCORED_FUNCID_RETURN_CALL_DONE)


#define TEESMC_TKCORED_FUNCID_RETURN_FIQ_DONE		6
#define TEESMC32_TKCORED_RETURN_FIQ_DONE \
	TEESMC_CALL_VAL(TEESMC_32, TEESMC_FAST_CALL, \
			TEESMC_OWNER_TRUSTED_OS_TKCORED, \
			TEESMC_TKCORED_FUNCID_RETURN_FIQ_DONE)
#define TEESMC64_TKCORED_RETURN_FIQ_DONE \
	TEESMC_CALL_VAL(TEESMC_64, TEESMC_FAST_CALL, \
			TEESMC_OWNER_TRUSTED_OS_TKCORED, \
			TEESMC_TKCORED_FUNCID_RETURN_FIQ_DONE)


#define TEESMC_TKCORED_FUNCID_SECURE_SERVICE_REQUEST	0x10
#define TEESMC32_TKCORED_SECURE_SERVICE_REQUEST \
	TEESMC_CALL_VAL(TEESMC_32, TEESMC_FAST_CALL, \
			TEESMC_OWNER_TRUSTED_OS_TKCORED, \
			TEESMC_TKCORED_FUNCID_SECURE_SERVICE_REQUEST)
#define TEESMC64_TKCORED_SECURE_SERVICE_REQUEST \
	TEESMC_CALL_VAL(TEESMC_64, TEESMC_FAST_CALL, \
			TEESMC_OWNER_TRUSTED_OS_TKCORED, \
			TEESMC_TKCORED_FUNCID_SECURE_SERVICE_REQUEST)

#endif
